CREATE TABLE t_station_profile(
id int(11) primary key NOT NULL auto_increment comment '項番',
station_CD varchar(16) default NULL comment '店舗コード',
com_CD varchar(16) default NULL comment '法人コード',
station_name varchar(128) NOT NULL comment '店舗名',
station_name_yomi varchar(128) default NULL comment '店舗名（カナ）',
trust_number varchar(16) NOT NULL comment '指定事業所番号',
zip varchar(16) NOT NULL comment '郵便番号',
address varchar(128) NOT NULL comment '所在地',
building varchar(128) default NULL comment '建物名・階数',
title varchar(128) default NULL comment '事業所説明見出し',
imple_area varchar(256) default NULL comment '実施区域',
visit_guidance int(11) NOT NULL comment '訪問実施状況',
station_function int(11) NOT NULL comment '事業所の機能',
hospital_link int(11) NOT NULL comment '医療機関併設の有無',
24_hour_aday int(11) NOT NULL comment '24時間体制',
pal_care int(11) NOT NULL comment '緩和ケア対応',
mental_care int(11) NOT NULL comment '精神疾患対応',
kids_care int(11) NOT NULL comment '小児対応',
dementia_care int(11) NOT NULL comment '認知症対応',
handicapped_care int(11) NOT NULL comment '障がい者対応',
nurse_fulltime int(11) NOT NULL comment '看護師常勤人数',
nurse_parttime int(11) NOT NULL comment '看護師非常勤人数',
pt_count int(11) NOT NULL comment 'PT：理学療法士の人数',
ot_count int(11) NOT NULL comment 'OT：作業療法士の人数',
st_count int(11) NOT NULL comment 'ST：言語聴覚士の人数',
entry_date datetime default NULL,
entry_user varchar(24) default NULL,
update_date datetime default NULL,
update_user varchar(24) default NULL,
delete_date datetime default NULL,
delete_user varchar(24) default NULL,
flag_set tinyint(1) NOT NULL,

KEY station_CD_index (station_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;